### ISSUE TITLE
Plot function/method does not give the correct `x` and `y` coordinates?

### ISSUE THREAD

**Issue by weikang9009** [martibosch/swisslandstats-geopy#4]
The `plot` method for the `LandDataFrame` class  does not visualize the correct `x` and `y` coordinates as shown below (this is a screenshot from the "overview" notebook):
![image](https://user-images.githubusercontent.com/7359284/60834715-27f39b00-a176-11e9-9d37-c6d8a5c97bc4.png)
The plotted figure should have the same`x` and `y` coordinates as the following figure which is produced from `rasterio`'s plotting function:
rasterio
![image](https://user-images.githubusercontent.com/7359284/60835231-73f30f80-a177-11e9-95aa-2a023ce53144.png)

this issue is related to https://github.com/openjournals/joss-reviews/issues/1511

**Comment by martibosch** [comment]
Hello Wei,
I have changed the code of `swisslandstats.plotting.plot_ndarray` (in turn used in `LandDataFrame.plot`) so that it uses `rasterio.plot.show` (instead of `matplotlib.pyplot.imshow`). This is released in v0.7.0 (I have also created [a change log](https://github.com/martibosch/swisslandstats-geopy/blob/master/CHANGELOG.md)). I have also updated the [example notebook](https://github.com/martibosch/swisslandstats-notebooks/blob/master/overview.ipynb) with the transformed plot coordinates.

Martí
